[package]
name = "lalrpop_workspace"
version = "0.1.0"
authors = ["Kevin Per <kevin.per@protonmail.com>"]
edition = "2018"

[[bin]]
path = "foo/src/main.rs"
name = "foo"

[dependencies]
lalrpop-util = "0.19.5"
regex = "1"
